---
- name: launch ec2 instances 
  ec2:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    instance_type: "{{ type }}"
    region: "{{ region }}"
    image: "{{ imageId }}"
    key_name: "{{ key }}"
    instance_tags:
      Name: "server-{{ item }}.{{ domain }}"
      project: "{{ Project }}"
    wait: yes
    assign_public_ip: yes
    vpc_subnet_id: "{{ subnet }}"
    group_id: ["{{ sg }}"]  
  with_sequence: start="{{ start_seq }}"  end="{{ end_seq }}"
