---
- name: installing mariadb  :)
  yum: name=mariadb-server state=present

- name: start service 
  service: name=mariadb state=started enabled=true

- name: clean up table
  shell: mysql -u root -e "drop table servers;" gateone
  ignore_errors: yes

- name: clean up database
  shell: mysql -u root -e "drop database gateone;"
  ignore_errors: yes

- name: create database
  shell: mysql -u root -e "create database gateone;"
  ignore_errors: yes

- name: create table
  shell: mysql -u root -e "create table servers (id int not null primary key auto_increment, name varchar(20),  eth0 varchar (15), eth1 varchar(15), online char(1), updated DATE);" gateone
  ignore_errors: yes

- name: copy data file over
  copy: src=data dest=/tmp/data

- name: load data
  shell: mysql -u root -e "LOAD DATA LOCAL INFILE '/tmp/data' INTO TABLE servers;" gateone

- name: grant access
  shell: mysql -u root -e "grant all privileges on gateone.* to 'dbuser'@'{{ node }}' identified by '{{ pass }}' with grant option;"

- name: grant access
  shell: mysql -u root -e "grant all privileges on gateone.* to 'dbuser'@'172.31.62.112' identified by '{{ pass }}' with grant option;"
