---
- name: get facts for LB
  hosts: localhost

  vars_files:
    - keypair.yml

  tasks:
  - local_action:
      module: ec2_remote_facts
      region: us-east-1
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      filters:
        instance-state-name: running
        "tag:Name": server-*.henry.com
    register: result

  - debug: var=result 
